name = "kv-value-retriever"
main = "src/index.js"
compatibility_date = "2023-05-15"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[[kv_namespaces]]
id = "b2932f29cf9b4f9caa6a22b5b21b9859"
binding = "ku"